name: Windows RDP
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download Ngrok
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Angelos24/RDP_Windows/main/ngrok.zip" -OutFile "ngrok.zip"
          Expand-Archive -Path "ngrok.zip" -DestinationPath "ngrok"
          cd ngrok
          .\ngrok.exe authtoken YOUR_NGROK_AUTH_TOKEN

      - name: Start Ngrok Tunnel
        run: |
          .\ngrok\ngrok.exe tcp 3389 --region us &

      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user Administrator /active:yes
          net user Administrator YOUR_PASSWORD

      - name: Keep the job running
        run: timeout /t 21600
