name: Windows RDP
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download Ngrok
        run: |
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
          Expand-Archive -Path "ngrok.zip" -DestinationPath "ngrok"
          .\ngrok\ngrok.exe authtoken YOUR_NGROK_AUTH_TOKEN

      - name: Start Ngrok Tunnel
        run: |
          Start-Process -NoNewWindow -FilePath .\ngrok\ngrok.exe -ArgumentList "tcp 3389 --region us"

      - name: Enable RDP (Run as SYSTEM)
        run: |
          Start-Process -FilePath "powershell.exe" -ArgumentList "-Command Start-Process 'powershell' -ArgumentList {Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name 'fDenyTSConnections' -Value 0; Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'} -Verb RunAs" -Verb RunAs

      - name: Enable Administrator & Set Password
        run: |
          net user Administrator /active:yes
          net user Administrator YOUR_PASSWORD

      - name: Keep the job running
        run: timeout /t 21600
